USE ca2;

DROP TABLE IF EXISTS CITYINFO;
CREATE TABLE CITYINFO (
	zip VARCHAR(5) PRIMARY KEY,
	city VARCHAR(50)
);

DROP TABLE IF EXISTS INFOENTITY;
CREATE TABLE INFOENTITY (
	id int PRIMARY KEY,
    email VARCHAR(50) UNIQUE
);

DROP TABLE IF EXISTS PHONE;
CREATE TABLE PHONE (
	pnum VARCHAR(8) PRIMARY KEY,
    description VARCHAR(50)
);